version: "3.8"

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql-conf-d:/etc/mysql/conf.d
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - demo
  mysql-setup:
    image: mysql:8.0.31
    container_name: mysql-setup
    depends_on:
      mysql:
        condition: service_healthy
    restart: "no"
    entrypoint: [ "bash", "-c", "/tmp/mysql-setup.sh"]
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./mysql-setup.sh:/tmp/mysql-setup.sh
      - ./mysql-setup.sql:/tmp/mysql-setup.sql
    networks:
      - demo
  redis:
    image: redislabs/redisgears:1.2.5
    container_name: redis
    restart: unless-stopped
    depends_on:
      - mysql-setup
    cap_add:
      - SYS_RESOURCE
    env_file: ./.env
    expose:
      - $REDIS_DOCKER_PORT
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT
    volumes:
      - ./target/redis-gears-for-caching-patterns-1.0.0.jar:/tmp/redis-gears-for-caching-patterns-1.0.0.jar
    stdin_open: true
    tty: true
    networks:
      - demo
  redis-setup:
    image: redislabs/redisgears:1.2.5
    container_name: redis-setup
    restart: "no"
    depends_on:
      - redis
    entrypoint: [ "bash", "-c", "/tmp/redis-setup.sh"]
    volumes:
      - ./target/redis-gears-for-caching-patterns-1.0.0.jar:/tmp/redis-gears-for-caching-patterns-1.0.0.jar
      - ./redis-setup.sh:/tmp/redis-setup.sh
    networks:
      - demo
  debezium:
    image: debezium/server
    container_name: debezium
    restart: "no"
    depends_on:
      - redis
    entrypoint: [ "echo", "Service debezium temporary disabled" ]
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $DEBEZIUM_LOCAL_PORT:$DEBEZIUM_DOCKER_PORT
    volumes:
      - ./debezium-conf:/debezium/conf
      - ./debezium-data:/debezium/data
    networks:
      - demo
networks:
  demo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16


